const _affirmations = [
  'You are a vessel of ancient wisdom and infinite light.',
  'The universe conspires in your favor, always.',
  'Your intuition is a sacred compass — trust it.',
  'You bloom beautifully in every season of your soul.',
  'Magic lives in the quiet moments you choose to notice.',
  'You are held by the moon and guided by the stars.',
  'Every breath you take is a prayer answered.',
  'Your sensitivity is your greatest strength.',
  'You are the author of a story worth telling.',
  'The sacred lives within you — you need only be still.',
  'You carry the wisdom of those who came before you.',
  'Your heart knows things your mind is still learning.',
  'You are enough, in this moment, exactly as you are.',
  'Beauty finds you because you have learned to seek it.',
  'The stars aligned for your becoming.',
  'You are a living ceremony of grace and resilience.',
  'Your light does not diminish the light of others — it multiplies it.',
  'Trust the timing of your unfolding.',
  'You are worthy of the love you so freely give.',
  'Every ending is a threshold into something sacred.',
  'The moon waxes and wanes — so too shall your seasons.',
  'You are rooted in love and reaching toward wonder.',
  'The world is richer because you are in it.',
  'Your dreams are dispatches from your deepest self.',
  'Rest is not retreat — it is preparation.',
  'You are a garden tended by time and intention.',
  'Softness is not weakness; it is the signature of the brave.',
  'You are held in the arms of the universe tonight.',
  'Every scar is a map of how far you have traveled.',
  'The sacred ordinary awaits your grateful eyes.',
  'You are a miracle wearing human skin.',
  'Your presence is the gift the world has been waiting for.',
  'The moon rises for you, faithful as your own heartbeat.',
  'You are woven from starlight and ancient song.',
  'Every morning you wake is a universe renewing its vow to you.',
  'You do not need to earn rest — you are worthy of ease.',
  'The quiet courage in your heart is the bravest thing.',
  'You are becoming something beautiful, even now.',
  'Let your softness be a radical act of self-love.',
  'Your story is still being written — and it is magnificent.',
  'You are the answer to a prayer someone once whispered.',
  'Grace follows you like moonlight through open windows.',
  'The sacred is not elsewhere — it lives in your ordinary days.',
  'You are allowed to take up space, in your fullness.',
  'Your joy is an act of devotion to the life you have been given.',
  'Healing happens in the spaces between your bravest moments.',
  'You are made of the same stuff as rivers — always finding your way.',
  'The universe has not forgotten you — it is working on your behalf.',
  'Be as gentle with yourself as you are with the things you love.',
  'You are a rare frequency in a world that needs your particular light.',
  'You are rooted deep enough to weather any storm.',
  'The moon knows your name and calls you beloved.',
  'What you tend to with love will always grow.',
  'You carry whole worlds inside you — never forget that.',
  'Every version of you has been doing the best she could.',
  'You are the culmination of every brave choice ever made for you.',
  'Beauty is not something you earn — it is something you are.',
  'Let the moon hold what is heavy tonight.',
  'You are sacred in your ordinary hours.',
  'The path ahead is lit by the light you already carry.',
];

String todaysAffirmation() {
  final now = DateTime.now();
  final seed = now.year * 10000 + now.month * 100 + now.day;
  return _affirmations[seed % _affirmations.length];
}
